springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREPRODUCTSERVICE_SERVER_PORT:8080}
  
spring:
  application:
    name: petstoreproductservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#        url: jdbc:postgresql://localhost:5432/petstoreproductservicedb
#        username: postgres
#        password: postgres
    url: jdbc:postgresql://petstoreserver.postgres.database.azure.com:5432/postgres
    username: postgres@petstoreserver
    password: ${PETSTORESERVER_POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true