springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREPRODUCTSERVICE_SERVER_PORT:8080}
  
spring:
  application:
    name: petstoreproductservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#        url: jdbc:postgresql://localhost:5432/petstoreproductservicedb
#        username: postgres
#        password: postgres
    url: ${PETSTORE-PRODUCT-SERVICE-DB-URL}
    username: ${PETSTORE-PRODUCT-SERVICE-DB-USERNAME}
    password: ${PETSTORE-PRODUCT-SERVICE-DB-PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://petstorekeyvault.vault.azure.net/
management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true